export const POST_CONTACT_US_EMAIL_INIT = "POST_CONTACT_US_EMAIL_INIT";
export const POST_CONTACT_US_EMAIL_FAILURE = "POST_CONTACT_US_EMAIL_FAILURE";
export const POST_CONTACT_US_EMAIL_SUCCESS = "POST_CONTACT_US_EMAIL_SUCCESS";
